---
# deploy  project
- name: Create {{ project.name }} nginx  directory
  file:
    path: /root/nginx_home/{{ project.name }}
    owner: root
    group: root
    mode: 777
    state: directory

- name: Check if {{ project.name }} nginx conf already exist
  stat:
    path: /root/nginx_home/{{ project.name }}/default.conf
  register: project_conf

- name: Create new {{ project.name }} conf
  template:
    src: ../templates/ejs.conf
    dest: /root/nginx_home/{{ project.name }}/default.conf
  when:  project_conf.stat.exists == false

- name: Run {{ project.name }} nginx server
  docker_container:
    name: "{{ project.name }}_nginx"
    image: nginx:alpine
    volumes:
      - /root/nginx_home/{{ project.name }}:/etc/nginx/conf.d
      - /root/jenkins_home/workspace/{{ project.name }}:/projects/{{ project.name }}
    ports:
      - 38003:80
    state: started

- name: Create nginx proxy pass for {{ project.name }}
  template:
    src: ../templates/proxy-pass.conf
    dest: /etc/nginx/conf.d/{{ project.name }}.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted
